sudo: required
services:
  - docker

before_install:
  - docker build -t mhamilton360/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mhamilton360/react-test npm test -- --coverage

after_success:
  - docker build -t mhamilton360/multi-client ./client
  - docker build -t mhamilton360/multi-nginx ./nginx
  - docker build -t mhamilton360/multi-server ./server
  - docker build -t mhamilton360/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take these images and push them to DockerHub
  - docker push mhamilton360/multi-client
  - docker push mhamilton360/multi-nginx
  - docker push mhamilton360/multi-server
  - docker push mhamilton360/multi-worker
